# Generated by Django 4.0.3 on 2023-07-20 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='wardrobe_bin',
            new_name='bin',
        ),
    ]
